//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


		public enum EnumLeaderBoard
		{
			NONE = 0,
			CgkImOzDqv8FEAIQBg = 2,
			CgkImOzDqv8FEAIQBw = 3,
			CgkImOzDqv8FEAIQCA = 4,
			CgkImOzDqv8FEAIQCQ = 5,
			
		};




